# /etc/mkinitcpio.conf for NovatOS live ISO
# Hooks order is critical:
#   - base:  base filesystem
#   - udev:  device nodes
#   - modconf: load modules from modprobe.d
#   - kms:   load KMS drivers EARLY so console + plymouth show in native res
#   - block: block devices
#   - filesystems: fs drivers
#   - plymouth:    splash screen
#   - keyboard / keymap / consolefont: localized console
#   - archiso:     the live-ISO magic
#   - encrypt:     in case user installs with LUKS later
#   - resume:      swap hibernate support

MODULES=(amdgpu radeon i915 nouveau virtio-gpu vmwgfx vboxvideo vfat ext4 btrfs)

BINARIES=()

FILES=()

HOOKS=(base udev modconf kms block keyboard keymap consolefont filesystems plymouth archiso encrypt resume)

COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-c -T0 --auto-threads=logical -19)
