[Autologin]
User=novatos
Session=hyprland

[Theme]
ThemeDir=/usr/share/sddm/themes
Current=novatos
CursorTheme=breeze_cursors
Font=Roboto

[Users]
MaximumUid=60513
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true

[Wayland]
DisplayCommand=/usr/share/sddm/wayland-session
SessionDir=/usr/share/wayland-sessions
EnableHiDPI=true
CompositorCommand=kwin_wayland --no-lockscreen
SessionCommand=/usr/share/sddm/scripts/wayland-session
