[Theme]
Name=NovatOS
Description=NovatOS login screen
Author=NovatOS Project
License=GPL-3.0
Type=sddm-theme
Website=https://github.com/salom600/NoovatOS
Screenshot=Preview.png
MainScript=Main.qml
ConfigFile=theme.conf
ThemeDir=.
TranslationsDirectory=translations
