# Calamares — packages module (post-install package operations)
# We don't try to install new packages during install (offline ISO),
# but we DO remove the live-only packages.

backend: pacman

operations:
  - try_remove:
      - virtualbox-guest-utils
      - virtualbox-guest-utils-nox
      - virtualbox-guest-modules-arch
      - open-vm-tools
      - open-vm-tools-desktop
      - archiso
      - mkinitcpio-archiso
      - chaoticaly-keyring
