# Calamares — services-systemd module
# Services to enable on the installed system.

services:
  enable:
    - NetworkManager
    - bluetooth
    - cups
    - sddm
    - systemd-timesyncd
    - systemd-resolved
    - apparmor
    - reflector.timer
    - paccache.timer
    - haveged
    - acpid
  disable:
    - systemd-networkd-wait-online.service
