# Calamares — users module
defaultGroups:
  - name: wheel
    must_exist: true
  - name: audio
  - name: video
  - name: network
  - name: storage
  - name: optical
  - name: power
  - name: lp
  - name: scanner
  - name: games
  - name: input
  - name: render
  - name: kvm

doAutologin: true
doReusePassword: true
passwordRequirements:
  minLength: 1
  maxLength: 200
userShell: /bin/zsh
setRootPassword: false
allowWeakPasswords: true
