# NovatOS Calamares — main settings
# Branch sequence: welcome → locale → keyboard → partitions → users → summary → install → post-install

modules-search: [ local ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - packages
    - luksbootkeyfile
    - plymouthcfg
    - initramfs
    - removeuser
    - initramfscfg
    - sources-yaml
    - initcpio
    - contextualprocess@novatos-postinstall
    - shellprocess@novatos-finalize
  - show:
    - finished

# Branding
branding: novatos

# Show the sliding panel of screenshots during installation
slideshow: "1.0"

# Don't quit on confirmation
dont-chroot: false

# Geolocation for picking default language
geolocation:
  style: none
  region: ""

# i18n of the installer
i18n:
  locale: en_US.UTF-8
  translationsDir: /usr/share/calamares/translations
  languagesDir: /usr/share/calamares/lang
